import { Injectable, ForbiddenException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { FinancialAuditService } from './financial-audit.service';
import { CfoAnalyticsService } from './cfo-analytics.service';
import { CFORecommendationCategory } from '@prisma/client';

// AI CFO can ONLY generate advisory recommendations.
// It MUST NOT: approve payments, execute payments, authorize transfers,
// approve refunds, modify financial authority, close accounting periods,
// reopen periods, alter posted journal entries, fabricate revenue/balances,
// alter bank balances, bypass approval, disable financial controls, modify kill switches.
const FORBIDDEN_CFO_AI_ACTIONS = [
  'APPROVE_PAYMENT', 'EXECUTE_PAYMENT', 'AUTHORIZE_TRANSFER', 'APPROVE_REFUND',
  'MODIFY_FINANCIAL_AUTHORITY', 'CLOSE_PERIOD', 'REOPEN_PERIOD',
  'ALTER_JOURNAL_ENTRY', 'FABRICATE_REVENUE', 'FABRICATE_BALANCE',
  'ALTER_BANK_BALANCE', 'BYPASS_APPROVAL', 'DISABLE_FINANCIAL_CONTROLS',
  'MODIFY_KILL_SWITCH',
] as const;

const AI_RECOMMENDATION_DISCLAIMER =
  'AI RECOMMENDATION ONLY — This is an advisory recommendation generated by an AI system. ' +
  'It has NOT been approved by any human. No financial action has been taken. ' +
  'This is NOT authoritative financial data. Human review and explicit authorization required before any action.';

@Injectable()
export class CfoAiService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly audit: FinancialAuditService,
    private readonly analytics: CfoAnalyticsService,
  ) {}

  private async verifyActor(actorId: string, companyId: string) {
    const chairman = await this.prisma.chairman.findUnique({ where: { id: actorId } });
    if (chairman) return null; // chairman always allowed
    const actor = await this.prisma.employee.findUnique({ where: { id: actorId } });
    if (!actor || actor.companyId !== companyId) throw new ForbiddenException('Actor does not belong to company');
    if (actor.status !== 'ACTIVE') throw new ForbiddenException('Actor is not active');
    return actor;
  }

  async generateRecommendations(companyId: string, actorId: string): Promise<{
    recommendations: Array<{
      category: CFORecommendationCategory; title: string; body: string;
      isAdvisory: true; disclaimer: string;
    }>;
  }> {
    await this.verifyActor(actorId, companyId);

    const runway = await this.analytics.getRunway(companyId, actorId);
    const ageing = await this.analytics.getPayablesAgeing(companyId, actorId);

    const recs: Array<{
      category: CFORecommendationCategory; title: string; body: string;
      reasoning: string; dataSnapshot: Record<string, unknown>;
    }> = [];

    // Low runway warning
    if (runway.estimatedRunwayMonths !== null && runway.estimatedRunwayMonths < 6) {
      recs.push({
        category: CFORecommendationCategory.RISK_ALERT,
        title: 'Low Cash Runway Warning',
        body: `Estimated runway is ${runway.estimatedRunwayMonths} months based on current burn rate. Consider reviewing expenses or accelerating revenue collection.`,
        reasoning: 'Runway below 6-month threshold is a financial risk signal.',
        dataSnapshot: { runway: runway.estimatedRunwayMonths, burnRatePaise: runway.monthlyBurnRatePaise },
      });
    }

    // Overdue payables
    if (ageing.overdue90plus > 0) {
      recs.push({
        category: CFORecommendationCategory.PAYABLE_MANAGEMENT,
        title: 'Critical Overdue Payables',
        body: `There are payables 90+ days overdue totaling ${ageing.overdue90plus} paise. Review vendor relationships and payment schedules.`,
        reasoning: 'Long-overdue payables can damage vendor relationships and creditworthiness.',
        dataSnapshot: { overdue90plus: ageing.overdue90plus },
      });
    }

    // Persist recommendations
    const saved = await Promise.all(recs.map(r =>
      this.prisma.cFORecommendation.create({
        data: {
          companyId,
          category: r.category,
          title: r.title,
          body: r.body,
          reasoning: r.reasoning,
          dataSnapshot: r.dataSnapshot as any,
          isAdvisory: true, // IMMUTABLE
          isActedOn: false,
          generatedById: actorId,
          disclaimer: AI_RECOMMENDATION_DISCLAIMER,
        },
      })
    ));

    await this.audit.record({
      companyId, actorId: 'AI_CFO', actorType: 'AI_AGENT',
      action: 'CFO_RECOMMENDATIONS_GENERATED',
      objectType: 'CFORecommendation', objectId: companyId,
      newValue: { count: recs.length, requestedBy: actorId },
    });

    return {
      recommendations: saved.map(r => ({
        category: r.category,
        title: r.title,
        body: r.body,
        isAdvisory: true as const,
        disclaimer: AI_RECOMMENDATION_DISCLAIMER,
      })),
    };
  }

  async getRecommendations(companyId: string, actorId: string) {
    await this.verifyActor(actorId, companyId);
    return this.prisma.cFORecommendation.findMany({
      where: { companyId, isActedOn: false },
      orderBy: { generatedAt: 'desc' },
    });
  }

  // Expose forbidden actions list for governance checks
  getForbiddenActions(): readonly string[] {
    return FORBIDDEN_CFO_AI_ACTIONS;
  }
}
