export interface AgentActionDefinition {
  type: string;
  description: string;
  requiredPermission: string;
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  isMutation: boolean;
  requiresChairmanApproval: boolean;
}

export const AgentActionRegistry: Record<string, AgentActionDefinition> = {
  VIEW_COMPANY: {
    type: 'VIEW_COMPANY',
    description: 'Retrieve general information about a company',
    requiredPermission: 'VIEW_COMPANY',
    riskLevel: 'LOW',
    isMutation: false,
    requiresChairmanApproval: false,
  },
  VIEW_DEPARTMENT: {
    type: 'VIEW_DEPARTMENT',
    description: 'Retrieve information about a department',
    requiredPermission: 'VIEW_COMPANY',
    riskLevel: 'LOW',
    isMutation: false,
    requiresChairmanApproval: false,
  },
  VIEW_EMPLOYEE: {
    type: 'VIEW_EMPLOYEE',
    description: 'Retrieve information about an employee',
    requiredPermission: 'VIEW_COMPANY',
    riskLevel: 'LOW',
    isMutation: false,
    requiresChairmanApproval: false,
  },
  VIEW_EMPLOYEE_SKILLS: {
    type: 'VIEW_EMPLOYEE_SKILLS',
    description: 'Retrieve skills for an employee',
    requiredPermission: 'VIEW_COMPANY',
    riskLevel: 'LOW',
    isMutation: false,
    requiresChairmanApproval: false,
  },
  VIEW_EMPLOYEE_HISTORY: {
    type: 'VIEW_EMPLOYEE_HISTORY',
    description: 'Retrieve employment history for an employee',
    requiredPermission: 'VIEW_COMPANY',
    riskLevel: 'LOW',
    isMutation: false,
    requiresChairmanApproval: false,
  },
  VIEW_MY_TASKS: {
    type: 'VIEW_MY_TASKS',
    description: 'Retrieve tasks assigned to the employee',
    requiredPermission: 'BASIC_ACCESS',
    riskLevel: 'LOW',
    isMutation: false,
    requiresChairmanApproval: false,
  },
  START_MY_TASK: {
    type: 'START_MY_TASK',
    description: 'Start an assigned task',
    requiredPermission: 'BASIC_ACCESS',
    riskLevel: 'LOW',
    isMutation: true,
    requiresChairmanApproval: false,
  },
  UPDATE_MY_TASK_PROGRESS: {
    type: 'UPDATE_MY_TASK_PROGRESS',
    description: 'Update progress for an assigned task',
    requiredPermission: 'BASIC_ACCESS',
    riskLevel: 'LOW',
    isMutation: true,
    requiresChairmanApproval: false,
  },
  SUBMIT_MY_TASK_FOR_REVIEW: {
    type: 'SUBMIT_MY_TASK_FOR_REVIEW',
    description: 'Submit an assigned task for review',
    requiredPermission: 'BASIC_ACCESS',
    riskLevel: 'LOW',
    isMutation: true,
    requiresChairmanApproval: false,
  },
  COMPLETE_MY_TASK: {
    type: 'COMPLETE_MY_TASK',
    description: 'Complete an assigned task',
    requiredPermission: 'BASIC_ACCESS',
    riskLevel: 'LOW',
    isMutation: true,
    requiresChairmanApproval: false,
  },
  UPDATE_EMPLOYEE_SKILL: {
    type: 'UPDATE_EMPLOYEE_SKILL',
    description: 'Update a skill proficiency for an employee',
    requiredPermission: 'MANAGE_EMPLOYEES',
    riskLevel: 'MEDIUM',
    isMutation: true,
    requiresChairmanApproval: false,
  },
  // Phase 6A: Receptionist Actions
  VIEW_COMPANY_CAPABILITIES: {
    type: 'VIEW_COMPANY_CAPABILITIES',
    description: 'View company wide capabilities and skills',
    requiredPermission: 'BASIC_ACCESS',
    riskLevel: 'LOW',
    isMutation: false,
    requiresChairmanApproval: false,
  },
  VIEW_DEPARTMENTS: {
    type: 'VIEW_DEPARTMENTS',
    description: 'View company departments',
    requiredPermission: 'BASIC_ACCESS',
    riskLevel: 'LOW',
    isMutation: false,
    requiresChairmanApproval: false,
  },
  VIEW_ACTIVE_WORKLOAD: {
    type: 'VIEW_ACTIVE_WORKLOAD',
    description: 'View current task load across company',
    requiredPermission: 'BASIC_ACCESS',
    riskLevel: 'LOW',
    isMutation: false,
    requiresChairmanApproval: false,
  },
  VIEW_CLIENT: {
    type: 'VIEW_CLIENT',
    description: 'View a client profile',
    requiredPermission: 'VIEW_CLIENTS',
    riskLevel: 'LOW',
    isMutation: false,
    requiresChairmanApproval: false,
  },
  CREATE_INQUIRY: {
    type: 'CREATE_INQUIRY',
    description: 'Create a new client inquiry',
    requiredPermission: 'MANAGE_INQUIRIES',
    riskLevel: 'MEDIUM',
    isMutation: true,
    requiresChairmanApproval: false,
  },
  REQUEST_MISSING_INFORMATION: {
    type: 'REQUEST_MISSING_INFORMATION',
    description: 'Draft a message to request missing info from client',
    requiredPermission: 'MANAGE_INQUIRIES',
    riskLevel: 'LOW',
    isMutation: true,
    requiresChairmanApproval: false,
  },
  UPDATE_INQUIRY_SUMMARY: {
    type: 'UPDATE_INQUIRY_SUMMARY',
    description: 'Update summary of client requirements',
    requiredPermission: 'MANAGE_INQUIRIES',
    riskLevel: 'LOW',
    isMutation: true,
    requiresChairmanApproval: false,
  },
  QUALIFY_INQUIRY: {
    type: 'QUALIFY_INQUIRY',
    description: 'Mark an inquiry as qualified and send to Sales',
    requiredPermission: 'MANAGE_INQUIRIES',
    riskLevel: 'MEDIUM',
    isMutation: true,
    requiresChairmanApproval: false,
  },
  // Phase 6B: Project Manager Actions
  VIEW_PROJECT: {
    type: 'VIEW_PROJECT',
    description: 'View details of a project',
    requiredPermission: 'VIEW_PROJECT',
    riskLevel: 'LOW',
    isMutation: false,
    requiresChairmanApproval: false,
  },
  VIEW_PROJECT_REQUIREMENTS: {
    type: 'VIEW_PROJECT_REQUIREMENTS',
    description: 'View requirements of a project',
    requiredPermission: 'VIEW_PROJECT',
    riskLevel: 'LOW',
    isMutation: false,
    requiresChairmanApproval: false,
  },
  VIEW_PROJECT_PLAN: {
    type: 'VIEW_PROJECT_PLAN',
    description: 'View the project plan',
    requiredPermission: 'VIEW_PROJECT',
    riskLevel: 'LOW',
    isMutation: false,
    requiresChairmanApproval: false,
  },
  VIEW_PROJECT_TASKS: {
    type: 'VIEW_PROJECT_TASKS',
    description: 'View all tasks for a project',
    requiredPermission: 'VIEW_PROJECT',
    riskLevel: 'LOW',
    isMutation: false,
    requiresChairmanApproval: false,
  },
  VIEW_PROJECT_TEAM: {
    type: 'VIEW_PROJECT_TEAM',
    description: 'View project team and assignments',
    requiredPermission: 'VIEW_PROJECT',
    riskLevel: 'LOW',
    isMutation: false,
    requiresChairmanApproval: false,
  },
  CREATE_PROJECT_PLAN: {
    type: 'CREATE_PROJECT_PLAN',
    description: 'Propose a new project plan',
    requiredPermission: 'MANAGE_PROJECT_PLAN',
    riskLevel: 'MEDIUM',
    isMutation: true,
    requiresChairmanApproval: false,
  },
  CREATE_PROJECT_REQUIREMENT: {
    type: 'CREATE_PROJECT_REQUIREMENT',
    description: 'Create a project requirement',
    requiredPermission: 'MANAGE_PROJECT_REQUIREMENTS',
    riskLevel: 'LOW',
    isMutation: true,
    requiresChairmanApproval: false,
  },
  CREATE_PROJECT_TASK: {
    type: 'CREATE_PROJECT_TASK',
    description: 'Create a task for the project',
    requiredPermission: 'MANAGE_PROJECT_TASKS',
    riskLevel: 'LOW',
    isMutation: true,
    requiresChairmanApproval: false,
  },
  UPDATE_PROJECT_TASK: {
    type: 'UPDATE_PROJECT_TASK',
    description: 'Update a task for the project',
    requiredPermission: 'MANAGE_PROJECT_TASKS',
    riskLevel: 'LOW',
    isMutation: true,
    requiresChairmanApproval: false,
  },
  PROPOSE_PROJECT_STAFFING: {
    type: 'PROPOSE_PROJECT_STAFFING',
    description: 'Propose an employee for the project team',
    requiredPermission: 'PROPOSE_PROJECT_STAFFING',
    riskLevel: 'MEDIUM',
    isMutation: true,
    requiresChairmanApproval: false,
  },
  // Phase 6C: Company Operations & Management Actions
  VIEW_COMPANY_METRICS: {
    type: 'VIEW_COMPANY_METRICS',
    description: 'View company KPI metrics',
    requiredPermission: 'VIEW_COMPANY_METRICS',
    riskLevel: 'LOW',
    isMutation: false,
    requiresChairmanApproval: false,
  },
  VIEW_DEPARTMENT_METRICS: {
    type: 'VIEW_DEPARTMENT_METRICS',
    description: 'View department KPI metrics',
    requiredPermission: 'VIEW_DEPARTMENT_METRICS',
    riskLevel: 'LOW',
    isMutation: false,
    requiresChairmanApproval: false,
  },
  VIEW_OPERATIONAL_ALERTS: {
    type: 'VIEW_OPERATIONAL_ALERTS',
    description: 'View operational alerts',
    requiredPermission: 'VIEW_OPERATIONAL_ALERTS',
    riskLevel: 'LOW',
    isMutation: false,
    requiresChairmanApproval: false,
  },
  CREATE_TRAINING_RECOMMENDATION: {
    type: 'CREATE_TRAINING_RECOMMENDATION',
    description: 'Create a training recommendation for an employee',
    requiredPermission: 'MANAGE_TRAINING',
    riskLevel: 'MEDIUM',
    isMutation: true,
    requiresChairmanApproval: false,
  },
  CREATE_PROMOTION_PROPOSAL: {
    type: 'CREATE_PROMOTION_PROPOSAL',
    description: 'Create a promotion proposal',
    requiredPermission: 'MANAGE_PROMOTIONS',
    riskLevel: 'MEDIUM',
    isMutation: true,
    requiresChairmanApproval: true,
  },
  CREATE_BONUS_PROPOSAL: {
    type: 'CREATE_BONUS_PROPOSAL',
    description: 'Create a bonus proposal',
    requiredPermission: 'MANAGE_BONUSES',
    riskLevel: 'MEDIUM',
    isMutation: true,
    requiresChairmanApproval: true,
  },
  CREATE_DISCIPLINARY_ACTION: {
    type: 'CREATE_DISCIPLINARY_ACTION',
    description: 'Issue a disciplinary action',
    requiredPermission: 'MANAGE_DISCIPLINE',
    riskLevel: 'HIGH',
    isMutation: true,
    requiresChairmanApproval: true,
  },
  CREATE_HIRING_REQUEST: {
    type: 'CREATE_HIRING_REQUEST',
    description: 'Create a hiring request',
    requiredPermission: 'MANAGE_HIRING',
    riskLevel: 'MEDIUM',
    isMutation: true,
    requiresChairmanApproval: true,
  },
  CREATE_WORKLOAD_REBALANCING_PROPOSAL: {
    type: 'CREATE_WORKLOAD_REBALANCING_PROPOSAL',
    description: 'Propose a task reassignment to balance workload',
    requiredPermission: 'MANAGE_WORKLOAD',
    riskLevel: 'MEDIUM',
    isMutation: true,
    requiresChairmanApproval: false,
  },
  // Phase 10: Communication & Collaboration Actions
  SEND_MESSAGE: {
    type: 'SEND_MESSAGE',
    description: 'Send a message in a conversation',
    requiredPermission: 'BASIC_ACCESS',
    riskLevel: 'LOW',
    isMutation: true,
    requiresChairmanApproval: false,
  },
  REPLY_TO_MESSAGE: {
    type: 'REPLY_TO_MESSAGE',
    description: 'Reply to a specific message',
    requiredPermission: 'BASIC_ACCESS',
    riskLevel: 'LOW',
    isMutation: true,
    requiresChairmanApproval: false,
  },
  VIEW_CONVERSATION: {
    type: 'VIEW_CONVERSATION',
    description: 'View messages in a conversation',
    requiredPermission: 'BASIC_ACCESS',
    riskLevel: 'LOW',
    isMutation: false,
    requiresChairmanApproval: false,
  },
  PROPOSE_MEETING: {
    type: 'PROPOSE_MEETING',
    description: 'Schedule a new meeting',
    requiredPermission: 'BASIC_ACCESS',
    riskLevel: 'LOW',
    isMutation: true,
    requiresChairmanApproval: false,
  },
  ADD_MEETING_AGENDA_ITEM: {
    type: 'ADD_MEETING_AGENDA_ITEM',
    description: 'Add an item to a meeting agenda',
    requiredPermission: 'BASIC_ACCESS',
    riskLevel: 'LOW',
    isMutation: true,
    requiresChairmanApproval: false,
  },
  // Phase 11: Company Knowledge Actions
  SEARCH_COMPANY_KNOWLEDGE: {
    type: 'SEARCH_COMPANY_KNOWLEDGE',
    description: 'Search the institutional knowledge base',
    requiredPermission: 'BASIC_ACCESS',
    riskLevel: 'LOW',
    isMutation: false,
    requiresChairmanApproval: false,
  },
  VIEW_KNOWLEDGE_PROVENANCE: {
    type: 'VIEW_KNOWLEDGE_PROVENANCE',
    description: 'View the sources and origins of a knowledge record',
    requiredPermission: 'BASIC_ACCESS',
    riskLevel: 'LOW',
    isMutation: false,
    requiresChairmanApproval: false,
  },
  PROPOSE_KNOWLEDGE: {
    type: 'PROPOSE_KNOWLEDGE',
    description: 'Propose a new knowledge record to be validated',
    requiredPermission: 'BASIC_ACCESS',
    riskLevel: 'LOW',
    isMutation: true,
    requiresChairmanApproval: false,
  },
  PROPOSE_KNOWLEDGE_UPDATE: {
    type: 'PROPOSE_KNOWLEDGE_UPDATE',
    description: 'Propose an update/supersession of an existing knowledge record',
    requiredPermission: 'BASIC_ACCESS',
    riskLevel: 'LOW',
    isMutation: true,
    requiresChairmanApproval: false,
  },
  REPORT_KNOWLEDGE_CONFLICT: {
    type: 'REPORT_KNOWLEDGE_CONFLICT',
    description: 'Report conflicting information in the knowledge base',
    requiredPermission: 'BASIC_ACCESS',
    riskLevel: 'LOW',
    isMutation: true,
    requiresChairmanApproval: false,
  },
  // Phase 12: Employee Intelligence Actions
  START_INTELLIGENCE_SESSION: { type: 'START_INTELLIGENCE_SESSION', description: 'Start an intelligence reasoning session', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  VIEW_RELEVANT_KNOWLEDGE: { type: 'VIEW_RELEVANT_KNOWLEDGE', description: 'View relevant company knowledge', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  VIEW_RELEVANT_MEMORY: { type: 'VIEW_RELEVANT_MEMORY', description: 'View relevant agent memory', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  VIEW_RELEVANT_COMMUNICATION: { type: 'VIEW_RELEVANT_COMMUNICATION', description: 'View relevant communication context', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  CREATE_WORK_PLAN: { type: 'CREATE_WORK_PLAN', description: 'Create a plan for the active task', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  VIEW_WORK_PLAN: { type: 'VIEW_WORK_PLAN', description: 'View an active work plan', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  UPDATE_WORK_PLAN: { type: 'UPDATE_WORK_PLAN', description: 'Update an active work plan', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  ASSESS_RISK: { type: 'ASSESS_RISK', description: 'Assess and record project/task risks', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  IDENTIFY_BLOCKER: { type: 'IDENTIFY_BLOCKER', description: 'Identify a blocker for current work', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  PROPOSE_DECISION: { type: 'PROPOSE_DECISION', description: 'Propose a structured decision', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  VIEW_DECISION_PROPOSAL: { type: 'VIEW_DECISION_PROPOSAL', description: 'View a decision proposal', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  REQUEST_HELP: { type: 'REQUEST_HELP', description: 'Request assistance from another employee', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  ESCALATE_ISSUE: { type: 'ESCALATE_ISSUE', description: 'Escalate an issue to management', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  REQUEST_TRAINING: { type: 'REQUEST_TRAINING', description: 'Request training for missing skills', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  REVIEW_OUTCOME: { type: 'REVIEW_OUTCOME', description: 'Review the outcome of a completed intelligence session', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  REVIEW_DECISION_PROPOSAL: { type: 'REVIEW_DECISION_PROPOSAL', description: 'Review a decision proposal', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  REQUEST_MORE_INFORMATION: { type: 'REQUEST_MORE_INFORMATION', description: 'Request more info for a proposal', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  APPROVE_DECISION: { type: 'APPROVE_DECISION', description: 'Approve a decision proposal', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'HIGH', isMutation: true, requiresChairmanApproval: false },
  REJECT_DECISION: { type: 'REJECT_DECISION', description: 'Reject a decision proposal', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },

  // Phase 13: AI Research & Development Actions
  VIEW_RESEARCH_PROPOSAL: { type: 'VIEW_RESEARCH_PROPOSAL', description: 'View a research proposal', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  VIEW_RESEARCH_PROJECT: { type: 'VIEW_RESEARCH_PROJECT', description: 'View a research project', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  VIEW_EXPERIMENT: { type: 'VIEW_EXPERIMENT', description: 'View an experiment', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  VIEW_DATASET: { type: 'VIEW_DATASET', description: 'View a dataset', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  VIEW_DATASET_LINEAGE: { type: 'VIEW_DATASET_LINEAGE', description: 'View dataset lineage', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  VIEW_MODEL_VERSION: { type: 'VIEW_MODEL_VERSION', description: 'View a model version', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  VIEW_EVALUATION_RESULTS: { type: 'VIEW_EVALUATION_RESULTS', description: 'View evaluation results', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  VIEW_RESEARCH_KNOWLEDGE: { type: 'VIEW_RESEARCH_KNOWLEDGE', description: 'View research knowledge', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  
  CREATE_RESEARCH_PROPOSAL: { type: 'CREATE_RESEARCH_PROPOSAL', description: 'Create a research proposal', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  PROPOSE_EXPERIMENT: { type: 'PROPOSE_EXPERIMENT', description: 'Propose an experiment', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  PROPOSE_EVALUATION: { type: 'PROPOSE_EVALUATION', description: 'Propose an evaluation', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  PROPOSE_SAFETY_EVALUATION: { type: 'PROPOSE_SAFETY_EVALUATION', description: 'Propose a safety evaluation', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  PROPOSE_MODEL_PROMOTION: { type: 'PROPOSE_MODEL_PROMOTION', description: 'Propose model promotion', requiredPermission: 'BASIC_ACCESS', riskLevel: 'HIGH', isMutation: true, requiresChairmanApproval: true },
  PROPOSE_ROLLBACK: { type: 'PROPOSE_ROLLBACK', description: 'Propose rollback', requiredPermission: 'BASIC_ACCESS', riskLevel: 'HIGH', isMutation: true, requiresChairmanApproval: true },

  // Phase 14: Model Development & Training Actions
  VIEW_TRAINING_CONFIGURATION: { type: 'VIEW_TRAINING_CONFIGURATION', description: 'View training configuration', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  CREATE_TRAINING_PROPOSAL: { type: 'CREATE_TRAINING_PROPOSAL', description: 'Create training configuration proposal', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  VIEW_TRAINING_RUN: { type: 'VIEW_TRAINING_RUN', description: 'View a training run status', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  REQUEST_TRAINING_RUN: { type: 'REQUEST_TRAINING_RUN', description: 'Request start of a training run', requiredPermission: 'BASIC_ACCESS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  CANCEL_TRAINING_RUN: { type: 'CANCEL_TRAINING_RUN', description: 'Cancel an active training run', requiredPermission: 'BASIC_ACCESS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  VIEW_CHECKPOINTS: { type: 'VIEW_CHECKPOINTS', description: 'View training checkpoints', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  VIEW_TRAINING_METRICS: { type: 'VIEW_TRAINING_METRICS', description: 'View training metrics', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  VIEW_MODEL_ARTIFACT: { type: 'VIEW_MODEL_ARTIFACT', description: 'View a completed model artifact', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  PROPOSE_MODEL_VERSION: { type: 'PROPOSE_MODEL_VERSION', description: 'Propose an artifact to become a ModelVersion', requiredPermission: 'BASIC_ACCESS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: true },
  REQUEST_MODEL_EVALUATION: { type: 'REQUEST_MODEL_EVALUATION', description: 'Request an evaluation on a new model', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  
  // Phase 15: Real Compute Actions
  VIEW_COMPUTE_CAPACITY: { type: 'VIEW_COMPUTE_CAPACITY', description: 'View available compute workers and resources', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  VIEW_TRAINING_QUEUE: { type: 'VIEW_TRAINING_QUEUE', description: 'View the training job queue', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  VIEW_TRAINING_JOB: { type: 'VIEW_TRAINING_JOB', description: 'View a specific training job', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  REQUEST_TRAINING_JOB: { type: 'REQUEST_TRAINING_JOB', description: 'Submit a training job to the queue', requiredPermission: 'BASIC_ACCESS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  VIEW_TRAINING_LOGS: { type: 'VIEW_TRAINING_LOGS', description: 'View logs for a training job', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  VIEW_ARTIFACTS: { type: 'VIEW_ARTIFACTS', description: 'View storage artifacts', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },

  // Phase 19 Autonomous Improvement Actions
  VIEW_IMPROVEMENT_SIGNALS: { type: 'VIEW_IMPROVEMENT_SIGNALS', description: 'View active model improvement signals', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  CREATE_IMPROVEMENT_HYPOTHESIS: { type: 'CREATE_IMPROVEMENT_HYPOTHESIS', description: 'Create a research hypothesis from an improvement signal', requiredPermission: 'BASIC_ACCESS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  PROPOSE_RESEARCH: { type: 'PROPOSE_RESEARCH', description: 'Propose a formal research project based on a hypothesis', requiredPermission: 'BASIC_ACCESS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: true },
  VIEW_MODEL_COMPARISON: { type: 'VIEW_MODEL_COMPARISON', description: 'View baseline vs candidate comparison results', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  PROPOSE_MODEL_DEPLOYMENT: { type: 'PROPOSE_MODEL_DEPLOYMENT', description: 'Propose deployment for a successful candidate model', requiredPermission: 'BASIC_ACCESS', riskLevel: 'HIGH', isMutation: true, requiresChairmanApproval: true },

  // Phase 23: Real-World Actions
  CREATE_CUSTOMER: { type: 'CREATE_CUSTOMER', description: 'Create a new customer lead', requiredPermission: 'BASIC_ACCESS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  DRAFT_CONTRACT: { type: 'DRAFT_CONTRACT', description: 'Draft a new contract', requiredPermission: 'BASIC_ACCESS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  COMMIT_CONTRACT: { type: 'COMMIT_CONTRACT', description: 'Commit an approved contract', requiredPermission: 'BASIC_ACCESS', riskLevel: 'HIGH', isMutation: true, requiresChairmanApproval: true },
  PROCESS_PAYMENT: { type: 'PROCESS_PAYMENT', description: 'Process an external payment', requiredPermission: 'BASIC_ACCESS', riskLevel: 'CRITICAL', isMutation: true, requiresChairmanApproval: true },
  PAYMENT_CAPTURE: { type: 'PAYMENT_CAPTURE', description: 'Capture an external payment', requiredPermission: 'BASIC_ACCESS', riskLevel: 'CRITICAL', isMutation: true, requiresChairmanApproval: true },
  PAYMENT_REFUND: { type: 'PAYMENT_REFUND', description: 'Refund an external payment', requiredPermission: 'BASIC_ACCESS', riskLevel: 'CRITICAL', isMutation: true, requiresChairmanApproval: true },
  SEND_EXTERNAL_COMMUNICATION: { type: 'SEND_EXTERNAL_COMMUNICATION', description: 'Send outbound external communication', requiredPermission: 'BASIC_ACCESS', riskLevel: 'HIGH', isMutation: true, requiresChairmanApproval: true },

  // Phase 26: Autonomous Sales & Business Development Actions
  VIEW_SALES_LEADS: { type: 'VIEW_SALES_LEADS', description: 'View sales leads for the company', requiredPermission: 'VIEW_SALES_LEADS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  VIEW_TARGET_ACCOUNTS: { type: 'VIEW_TARGET_ACCOUNTS', description: 'View target accounts for the company', requiredPermission: 'VIEW_TARGET_ACCOUNTS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  VIEW_OPPORTUNITIES: { type: 'VIEW_OPPORTUNITIES', description: 'View sales opportunities', requiredPermission: 'VIEW_OPPORTUNITIES', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  VIEW_PIPELINE_METRICS: { type: 'VIEW_PIPELINE_METRICS', description: 'View pipeline metrics and analytics', requiredPermission: 'VIEW_PIPELINE_METRICS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  LOG_SALES_ACTIVITY: { type: 'LOG_SALES_ACTIVITY', description: 'Log a non-external sales activity', requiredPermission: 'LOG_SALES_ACTIVITY', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  GENERATE_QUALIFICATION_ASSESSMENT: { type: 'GENERATE_QUALIFICATION_ASSESSMENT', description: 'Generate a qualification assessment recommendation (non-authoritative)', requiredPermission: 'GENERATE_QUALIFICATION_ASSESSMENT', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  GENERATE_OPPORTUNITY_SCORE: { type: 'GENERATE_OPPORTUNITY_SCORE', description: 'Generate an opportunity score with provenance (non-authoritative)', requiredPermission: 'GENERATE_OPPORTUNITY_SCORE', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  GENERATE_SALES_RECOMMENDATION: { type: 'GENERATE_SALES_RECOMMENDATION', description: 'Generate sales manager recommendations (non-authoritative)', requiredPermission: 'GENERATE_SALES_RECOMMENDATION', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  DRAFT_OUTREACH_MESSAGE: { type: 'DRAFT_OUTREACH_MESSAGE', description: 'Draft an outreach message for human review (does NOT send)', requiredPermission: 'DRAFT_OUTREACH_MESSAGE', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },

  // Phase 27: Autonomous Marketing & Brand — Advisory actions
  RESEARCH_MARKET: { type: 'RESEARCH_MARKET', description: 'Research markets and generate intelligence (advisory)', requiredPermission: 'RESEARCH_MARKET', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  ANALYZE_AUDIENCE: { type: 'ANALYZE_AUDIENCE', description: 'Analyze target audiences and personas (advisory)', requiredPermission: 'ANALYZE_AUDIENCE', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  GENERATE_CONTENT: { type: 'GENERATE_CONTENT', description: 'Generate content draft for human review (advisory — NOT approved)', requiredPermission: 'GENERATE_CONTENT', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  DRAFT_CAMPAIGN: { type: 'DRAFT_CAMPAIGN', description: 'Draft a campaign plan for human review (advisory)', requiredPermission: 'DRAFT_CAMPAIGN', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  SCORE_CONTENT: { type: 'SCORE_CONTENT', description: 'Score content for brand consistency (advisory — NOT approval)', requiredPermission: 'SCORE_CONTENT', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  RECOMMEND_CHANNEL: { type: 'RECOMMEND_CHANNEL', description: 'Recommend marketing channels (advisory)', requiredPermission: 'RECOMMEND_CHANNEL', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  RECOMMEND_TIMING: { type: 'RECOMMEND_TIMING', description: 'Recommend publication timing (advisory)', requiredPermission: 'RECOMMEND_TIMING', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  ANALYZE_CAMPAIGN: { type: 'ANALYZE_CAMPAIGN', description: 'Analyze campaign performance (advisory)', requiredPermission: 'ANALYZE_CAMPAIGN', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  RECOMMEND_OPTIMIZATION: { type: 'RECOMMEND_OPTIMIZATION', description: 'Recommend campaign/content optimizations (advisory)', requiredPermission: 'RECOMMEND_OPTIMIZATION', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  VIEW_BRAND: { type: 'VIEW_BRAND', description: 'View brand profile and guidelines', requiredPermission: 'VIEW_BRAND', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  VIEW_ANALYTICS: { type: 'VIEW_ANALYTICS', description: 'View marketing analytics (read-only)', requiredPermission: 'VIEW_ANALYTICS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  // Phase 27: Restricted — require human actor, never AI-only
  CREATE_CAMPAIGN: { type: 'CREATE_CAMPAIGN', description: 'Create a marketing campaign (human required)', requiredPermission: 'CREATE_CAMPAIGN', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  MODIFY_CAMPAIGN: { type: 'MODIFY_CAMPAIGN', description: 'Modify an existing campaign (human required)', requiredPermission: 'MODIFY_CAMPAIGN', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  SCHEDULE_CONTENT: { type: 'SCHEDULE_CONTENT', description: 'Schedule content for publication (human required)', requiredPermission: 'SCHEDULE_CONTENT', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  REQUEST_PUBLICATION: { type: 'REQUEST_PUBLICATION', description: 'Request external publication of content (human required)', requiredPermission: 'REQUEST_PUBLICATION', riskLevel: 'HIGH', isMutation: true, requiresChairmanApproval: true },
  // Phase 27: Publication capability (production gate)
  MARKETING_PUBLICATION: { type: 'MARKETING_PUBLICATION', description: 'Execute external marketing content publication (production gate required)', requiredPermission: 'MARKETING_PUBLICATION', riskLevel: 'HIGH', isMutation: true, requiresChairmanApproval: true },
  // Phase 28: Finance advisory AI actions (read-only analytics — never financial mutations)
  ANALYZE_FINANCIALS: { type: 'ANALYZE_FINANCIALS', description: 'Analyze financial data and generate insights (advisory)', requiredPermission: 'ANALYZE_FINANCIALS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  GENERATE_CFO_RECOMMENDATIONS: { type: 'GENERATE_CFO_RECOMMENDATIONS', description: 'Generate AI CFO advisory recommendations (advisory — no financial authority)', requiredPermission: 'GENERATE_CFO_RECOMMENDATIONS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  FORECAST_FINANCIALS: { type: 'FORECAST_FINANCIALS', description: 'Generate financial forecasts (advisory — isAdvisory=true always)', requiredPermission: 'FORECAST_FINANCIALS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  VIEW_FINANCIAL_REPORTS: { type: 'VIEW_FINANCIAL_REPORTS', description: 'View financial reports and analytics (read-only)', requiredPermission: 'VIEW_FINANCIAL_REPORTS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  // Phase 28: Payment execution (human-only, production gate required)
  PAYMENT_EXECUTION: { type: 'PAYMENT_EXECUTION', description: 'Execute payment requests (human actor required, production gate)', requiredPermission: 'PAYMENT_EXECUTION', riskLevel: 'CRITICAL', isMutation: true, requiresChairmanApproval: true },
  // Phase 29: Workforce advisory AI actions (read-only — never workforce mutations)
  ANALYZE_WORKFORCE: { type: 'ANALYZE_WORKFORCE', description: 'Analyze workforce data and generate insights (advisory)', requiredPermission: 'ANALYZE_WORKFORCE', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  RECOMMEND_TRAINING: { type: 'RECOMMEND_TRAINING', description: 'Recommend training programs for employees (advisory)', requiredPermission: 'RECOMMEND_TRAINING', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  RECOMMEND_PROMOTION: { type: 'RECOMMEND_PROMOTION', description: 'Recommend employee promotion (advisory — cannot self-promote)', requiredPermission: 'RECOMMEND_PROMOTION', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  EVALUATE_PERFORMANCE: { type: 'EVALUATE_PERFORMANCE', description: 'Evaluate subordinate performance (advisory)', requiredPermission: 'EVALUATE_PERFORMANCE', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  // Phase 29: Workforce mutations (require human authorization, approval binding)
  HIRE_EMPLOYEE: { type: 'HIRE_EMPLOYEE', description: 'Complete employee hiring (human authorized, approval required)', requiredPermission: 'HIRE_EMPLOYEE', riskLevel: 'HIGH', isMutation: true, requiresChairmanApproval: false },
  PROVISION_AI_WORKER: { type: 'PROVISION_AI_WORKER', description: 'Provision AI worker (approval required, no HIGH_AUTONOMY without Chairman)', requiredPermission: 'PROVISION_AI_WORKER', riskLevel: 'HIGH', isMutation: true, requiresChairmanApproval: true },
  TERMINATE_EMPLOYEE: { type: 'TERMINATE_EMPLOYEE', description: 'Terminate employee (human authorized, not for AI self-termination of privileged employees)', requiredPermission: 'TERMINATE_EMPLOYEE', riskLevel: 'CRITICAL', isMutation: true, requiresChairmanApproval: false },

  // Phase 30: Autonomous Company Management — advisory/read actions (never mutate authoritative domain state)
  VIEW_COMPANY_STATE: { type: 'VIEW_COMPANY_STATE', description: 'View aggregated company state snapshot (read-only, non-authoritative)', requiredPermission: 'VIEW_COMPANY_METRICS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  VIEW_HEALTH_SNAPSHOT: { type: 'VIEW_HEALTH_SNAPSHOT', description: 'View latest company health analysis (advisory, not authoritative)', requiredPermission: 'VIEW_COMPANY_METRICS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  ANALYZE_COMPANY_HEALTH: { type: 'ANALYZE_COMPANY_HEALTH', description: 'Run company health analysis (advisory — result is analysis, not fact)', requiredPermission: 'VIEW_COMPANY_METRICS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  VIEW_OBJECTIVES: { type: 'VIEW_OBJECTIVES', description: 'View company objectives (read-only)', requiredPermission: 'VIEW_COMPANY_METRICS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  PROPOSE_OBJECTIVE: { type: 'PROPOSE_OBJECTIVE', description: 'Propose a company objective for review (advisory — not self-approving)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  VIEW_KPIS: { type: 'VIEW_KPIS', description: 'View company KPIs (read-only)', requiredPermission: 'VIEW_COMPANY_METRICS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  UPDATE_KPI_VALUE: { type: 'UPDATE_KPI_VALUE', description: 'Update KPI current value (isAdvisory=true unless authorized source)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  PROPOSE_EXECUTIVE_DECISION: { type: 'PROPOSE_EXECUTIVE_DECISION', description: 'Propose a management decision (advisory — cannot self-approve)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  VIEW_EXECUTIVE_DECISIONS: { type: 'VIEW_EXECUTIVE_DECISIONS', description: 'View executive decisions (read-only)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  APPROVE_EXECUTIVE_DECISION: { type: 'APPROVE_EXECUTIVE_DECISION', description: 'Approve an executive decision (cannot be proposer — approval binding enforced)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'HIGH', isMutation: true, requiresChairmanApproval: false },
  PROPOSE_RESOURCE_ALLOCATION: { type: 'PROPOSE_RESOURCE_ALLOCATION', description: 'Propose resource reallocation (advisory — actual domain mutations require separate authorization)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  VIEW_COMPANY_RISKS: { type: 'VIEW_COMPANY_RISKS', description: 'View company risks (read-only)', requiredPermission: 'VIEW_COMPANY_METRICS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  IDENTIFY_COMPANY_RISK: { type: 'IDENTIFY_COMPANY_RISK', description: 'Identify and record a company risk (advisory — cannot self-suppress own AI risks)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  VIEW_COMPANY_OPPORTUNITIES: { type: 'VIEW_COMPANY_OPPORTUNITIES', description: 'View company opportunities (read-only)', requiredPermission: 'VIEW_COMPANY_METRICS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  IDENTIFY_OPPORTUNITY: { type: 'IDENTIFY_OPPORTUNITY', description: 'Identify a company opportunity (advisory)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  CREATE_ESCALATION: { type: 'CREATE_ESCALATION', description: 'Create a Chairman escalation (priority changes auditable — cannot self-escalate to CRITICAL without justification)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'HIGH', isMutation: true, requiresChairmanApproval: false },
  VIEW_ESCALATIONS: { type: 'VIEW_ESCALATIONS', description: 'View Chairman escalations (read-only)', requiredPermission: 'VIEW_COMPANY_METRICS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  TRIGGER_MANAGEMENT_CYCLE: { type: 'TRIGGER_MANAGEMENT_CYCLE', description: 'Trigger a management cycle (idempotent per period — cannot run duplicate cycles)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  RECORD_ORG_MEMORY: { type: 'RECORD_ORG_MEMORY', description: 'Record organizational memory (append-only — cannot overwrite historical results)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  // Phase 30: Restricted management actions — require approval or Chairman
  APPROVE_BUDGET_RECOMMENDATION: { type: 'APPROVE_BUDGET_RECOMMENDATION', description: 'Approve a budget recommendation decision (requires approval binding — no direct financial mutation)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'HIGH', isMutation: true, requiresChairmanApproval: true },
  APPROVE_STRATEGIC_DECISION: { type: 'APPROVE_STRATEGIC_DECISION', description: 'Approve a strategic management decision (Chairman level)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'CRITICAL', isMutation: true, requiresChairmanApproval: true },
  DISABLE_AUTONOMOUS_MANAGEMENT: { type: 'DISABLE_AUTONOMOUS_MANAGEMENT', description: 'Disable autonomous management system (kill switch — Chairman only, not self-disableable)', requiredPermission: 'CHAIRMAN_ONLY', riskLevel: 'CRITICAL', isMutation: true, requiresChairmanApproval: true },

  // Phase 31: Autonomous Strategy Engine — analysis/advisory actions
  VIEW_STRATEGIC_STATE: { type: 'VIEW_STRATEGIC_STATE', description: 'View strategic state snapshot (ANALYSIS — non-authoritative)', requiredPermission: 'VIEW_COMPANY_METRICS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  VIEW_STRATEGIC_PORTFOLIO: { type: 'VIEW_STRATEGIC_PORTFOLIO', description: 'View strategic portfolio analysis (ANALYSIS)', requiredPermission: 'VIEW_COMPANY_METRICS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  CREATE_STRATEGIC_THEME: { type: 'CREATE_STRATEGIC_THEME', description: 'Create a strategic theme (organizational concept — no authority)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  PROPOSE_STRATEGIC_INITIATIVE: { type: 'PROPOSE_STRATEGIC_INITIATIVE', description: 'Propose a strategic initiative (advisory — cannot self-approve)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  GENERATE_STRATEGIC_OPTION: { type: 'GENERATE_STRATEGIC_OPTION', description: 'Generate a strategic option for evaluation (RECOMMENDATION — cannot self-select)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  EVALUATE_STRATEGIC_OPTION: { type: 'EVALUATE_STRATEGIC_OPTION', description: 'Evaluate a strategic option (cannot self-evaluate own option)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  GENERATE_SCENARIO: { type: 'GENERATE_SCENARIO', description: 'Generate a strategic scenario (ANALYSIS — never becomes authoritative fact)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  CREATE_STRATEGIC_FORECAST: { type: 'CREATE_STRATEGIC_FORECAST', description: 'Create a strategic forecast (FORECAST — never writes to financial ledger)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  TRIGGER_STRATEGY_REVIEW: { type: 'TRIGGER_STRATEGY_REVIEW', description: 'Trigger a strategy review cycle (idempotent per day — no auto-execution of strategy)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  CREATE_STRATEGIC_EXPERIMENT: { type: 'CREATE_STRATEGIC_EXPERIMENT', description: 'Create a strategic experiment (bounded by resourceLimit — no unlimited resource commitment)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },

  // Phase 31: High-impact strategic actions — require Chairman approval
  APPROVE_STRATEGIC_INITIATIVE: { type: 'APPROVE_STRATEGIC_INITIATIVE', description: 'Approve a strategic initiative (cannot be initiative owner — Chairman level for irreversible)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'HIGH', isMutation: true, requiresChairmanApproval: false },
  APPROVE_IRREVERSIBLE_STRATEGY: { type: 'APPROVE_IRREVERSIBLE_STRATEGY', description: 'Approve irreversible strategic initiative (Chairman required — highest commitment level)', requiredPermission: 'CHAIRMAN_ONLY', riskLevel: 'CRITICAL', isMutation: true, requiresChairmanApproval: true },
  DISABLE_AUTONOMOUS_STRATEGY: { type: 'DISABLE_AUTONOMOUS_STRATEGY', description: 'Disable autonomous strategy engine (kill switch — Chairman only)', requiredPermission: 'CHAIRMAN_ONLY', riskLevel: 'CRITICAL', isMutation: true, requiresChairmanApproval: true },

  // Phase 32: AEVORA Research Lab — read/view actions
  VIEW_RESEARCH: { type: 'VIEW_RESEARCH', description: 'View research projects, questions, and findings (read-only)', requiredPermission: 'VIEW_COMPANY_METRICS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  VIEW_EXPERIMENTS: { type: 'VIEW_EXPERIMENTS', description: 'View experiments and runs (read-only)', requiredPermission: 'VIEW_COMPANY_METRICS', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },

  // Phase 32: Research Lab — propose/create (advisory, no mutation authority)
  CREATE_RESEARCH_PROJECT: { type: 'CREATE_RESEARCH_PROJECT', description: 'Create a research lab project (advisory — cannot self-approve)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  CREATE_RESEARCH_QUESTION: { type: 'CREATE_RESEARCH_QUESTION', description: 'Create a research question (advisory — no production mutation)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  PROPOSE_HYPOTHESIS: { type: 'PROPOSE_HYPOTHESIS', description: 'Propose a research hypothesis (always isAdvisory — cannot self-validate)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  CREATE_EXPERIMENT: { type: 'CREATE_EXPERIMENT', description: 'Create a research experiment (PRODUCTION environment blocked — sandbox only)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  RUN_EXPERIMENT: { type: 'RUN_EXPERIMENT', description: 'Queue an experiment run (sandbox/staging only — never PRODUCTION)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  CANCEL_EXPERIMENT: { type: 'CANCEL_EXPERIMENT', description: 'Cancel a queued or running experiment', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  RECORD_RESULT: { type: 'RECORD_RESULT', description: 'Record an experiment result (immutable — one per run, always isAdvisory)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  EVALUATE_RESULT: { type: 'EVALUATE_RESULT', description: 'Evaluate an experiment result (cannot self-evaluate own result)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  ADD_EVIDENCE: { type: 'ADD_EVIDENCE', description: 'Add evidence item to a hypothesis (always isAdvisory — AI estimate never becomes authoritative fact)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  CREATE_FINDING: { type: 'CREATE_FINDING', description: 'Create a research finding (always DRAFT — cannot self-validate)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  VALIDATE_FINDING: { type: 'VALIDATE_FINDING', description: 'Validate or reject a research finding (cannot validate own finding)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  CREATE_REPRODUCTION: { type: 'CREATE_REPRODUCTION', description: 'Record a reproduction attempt (both runs must be COMPLETED, cannot reuse same run)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  CREATE_RESEARCH_RECOMMENDATION: { type: 'CREATE_RESEARCH_RECOMMENDATION', description: 'Create a research recommendation (always isAdvisory — never directly mutates strategy, finance, or workforce)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  ARCHIVE_RESEARCH: { type: 'ARCHIVE_RESEARCH', description: 'Archive research findings or questions (non-destructive — reversible status change)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },

  // Phase 32: Kill switch — Chairman only
  DISABLE_AUTONOMOUS_RESEARCH: { type: 'DISABLE_AUTONOMOUS_RESEARCH', description: 'Disable autonomous research engine (kill switch — Chairman only, not self-disableable)', requiredPermission: 'CHAIRMAN_ONLY', riskLevel: 'CRITICAL', isMutation: true, requiresChairmanApproval: true },

  // Phase 33: Model Platform — advisory intelligence infrastructure
  VIEW_MODEL_PLATFORM: { type: 'VIEW_MODEL_PLATFORM', description: 'View model platform providers, models, and configurations (advisory only)', requiredPermission: 'VIEW_COMPANY', riskLevel: 'LOW', isMutation: false, requiresChairmanApproval: false },
  REGISTER_PROVIDER: { type: 'REGISTER_PROVIDER', description: 'Register a new AI provider (advisory — no production system mutation)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  REGISTER_MODEL: { type: 'REGISTER_MODEL', description: 'Register a model under a provider (advisory — isAdvisory:true enforced)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  ADVANCE_MODEL_DEPLOYMENT: { type: 'ADVANCE_MODEL_DEPLOYMENT', description: 'Advance model deployment state (human approval required for APPROVED state — AI cannot self-approve)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'HIGH', isMutation: true, requiresChairmanApproval: false },
  EXECUTE_INFERENCE: { type: 'EXECUTE_INFERENCE', description: 'Execute inference via governed model platform (advisory output — isAdvisory:true, kill switch enforced)', requiredPermission: 'BASIC_ACCESS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  MANAGE_KILL_SWITCH: { type: 'MANAGE_KILL_SWITCH', description: 'Activate or deactivate model platform kill switch (fail-closed — blocks all inference when active)', requiredPermission: 'CHAIRMAN_ONLY', riskLevel: 'CRITICAL', isMutation: true, requiresChairmanApproval: true },
  MANAGE_ROUTE_POLICY: { type: 'MANAGE_ROUTE_POLICY', description: 'Create or deactivate model routing policies', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'MEDIUM', isMutation: true, requiresChairmanApproval: false },
  MANAGE_PROMPT_TEMPLATES: { type: 'MANAGE_PROMPT_TEMPLATES', description: 'Create and version prompt templates (advisory — isAdvisory:true)', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
  RECORD_MODEL_HEALTH: { type: 'RECORD_MODEL_HEALTH', description: 'Record health check results for providers and models', requiredPermission: 'MANAGE_DECISIONS', riskLevel: 'LOW', isMutation: true, requiresChairmanApproval: false },
};
